service: calculator-serverless

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-west-1
  stage: dev

plugins:
  - serverless-offline


functions:
  add:
    handler: add.add
    events:
      - http:
          path: /add
          method: post
          cors: true
  auth:
    handler: auth.auth
    events:
      - http:
          path: /auth
          method: post
          cors: true
