service: calculator-serverless

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-west-1
  stage: dev


functions:
  hello:
    handler: handler.hello

  add:
    handler: add.add
    events:
      - http:
          path: /add
          method: post
          cors: true
