service: calculator-serverless

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-west-1
  stage: dev

plugins:
  - serverless-offline

functions:
  add:
    handler: add.add
    events:
      - http:
          path: /add
          method: post
          cors: true

  auth:
    handler: auth.auth
    environment:
      CLIENT_ID: ${ssm:/calculator/dev/clientId}
      URL: ${ssm:/calculator/dev/oAuthurl}
    events:
      - http:
          path: /auth
          method: post
          cors: true

  addition:
    handler: addition.handler
    events:
      - http:
          path: /addition
          method: post
          cors: true
          authorizer: authorizerFunction

  subtraction:
    handler: subtraction.handler
    events:
      - http:
          path: /subtraction
          method: post
          cors: true
          authorizer: authorizerFunction

  multiplication:
    handler: multiplication.handler
    events:
      - http:
          path: /multiplication
          method: post
          cors: true
          authorizer: authorizerFunction

  division:
    handler: division.handler
    events:
      - http:
          path: /division
          method: post
          cors: true
          authorizer: authorizerFunction

  authorizerFunction:
    handler: handler.authorize
    environment:
      ISS: ${ssm:/calculator/dev/ISS}

  auther:
    handler: handler.authorize
    environment:
      ISS: ${ssm:/calculator/dev/ISS}
    events:
      - http:
          path: /auther
          method: get
          cors: true

  usercontent:
    handler: userContent.handler
    events:
      - http:
          path: /user
          method: get
          cors: true
